# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-08-25T13:19:17+00:00

from __future__ import annotations

from typing import Annotated, Optional, Union

from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import AfterValidator, constr

from . import service
from .generated.api.models import (
    CallToolInput,
    CallToolResult,
    ErrorDetail,
    HTTPValidationError,
    McpInput,
    McpListResponse,
    McpName,
    McpNameResponse,
    McpServerConfig,
    McpToolListResponse,
    McpUsageResponse,
    ProbeError,
    ProbeOk,
)


def _mcp_name(value: str) -> str:
    # Generated McpName is a RootModel; FastAPI path params must be scalars.
    return McpName.model_validate(value).root


McpNamePath = Annotated[str, AfterValidator(_mcp_name)]

app = FastAPI(
    title='MCP',
    description='MCP registry service',
    version='0.1.0',
)


@app.get('/api/v1/mcps', response_model=McpListResponse)
def list_mcps() -> McpListResponse:
    """
    List all MCP servers
    """
    return service.list_mcps()


@app.get(
    '/api/v1/mcps/{name}',
    response_model=McpServerConfig,
    responses={'404': {'model': ErrorDetail}, '422': {'model': HTTPValidationError}},
)
def get_mcp(
    name: McpNamePath,
) -> Union[McpServerConfig, ErrorDetail, HTTPValidationError]:
    """
    Get an MCP server by name
    """
    return service.get_mcp(name)


@app.post(
    '/api/v1/mcps/{name}',
    response_model=McpNameResponse,
    status_code=201,
    responses={'409': {'model': ErrorDetail}, '422': {'model': HTTPValidationError}},
)
def create_mcp(
    name: McpNamePath, body: McpInput = ...
) -> Union[McpNameResponse, ErrorDetail, HTTPValidationError]:
    """
    Create an MCP server
    """
    return service.create_mcp(name, body)


@app.put(
    '/api/v1/mcps/{name}',
    response_model=McpNameResponse,
    responses={'404': {'model': ErrorDetail}, '422': {'model': HTTPValidationError}},
)
def update_mcp(
    name: McpNamePath, body: McpInput = ...
) -> Union[McpNameResponse, ErrorDetail, HTTPValidationError]:
    """
    Replace an MCP server
    """
    return service.update_mcp(name, body)


@app.delete(
    '/api/v1/mcps/{name}',
    response_model=None,
    status_code=204,
    responses={
        '404': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
        '409': {'model': ErrorDetail},
        '502': {'model': ErrorDetail},
    },
)
def delete_mcp(
    name: McpNamePath,
) -> Optional[Union[ErrorDetail, HTTPValidationError]]:
    """
    Delete an MCP server
    """
    service.delete_mcp(name)


@app.get(
    '/api/v1/mcps/{name}/tools',
    response_model=McpToolListResponse,
    responses={
        '400': {'model': ErrorDetail},
        '404': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
        '502': {'model': ErrorDetail},
    },
)
async def list_mcp_tools(
    name: McpNamePath,
) -> Union[McpToolListResponse, ErrorDetail, HTTPValidationError]:
    """
    List tools exposed by an MCP server
    """
    return await service.list_mcp_tools(name)


@app.post(
    '/api/v1/mcps/{name}/tools/{tool_name}/call',
    response_model=CallToolResult,
    responses={
        '400': {'model': ErrorDetail},
        '404': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
        '502': {'model': ErrorDetail},
    },
)
async def call_mcp_tool(
    name: McpNamePath, tool_name: constr(min_length=1) = ..., body: CallToolInput = ...
) -> Union[CallToolResult, ErrorDetail, HTTPValidationError]:
    """
    Call a tool on an MCP server
    """
    return await service.call_mcp_tool(name, tool_name, body)


@app.get(
    '/api/v1/mcps/{name}/usage',
    response_model=McpUsageResponse,
    responses={
        '404': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
        '502': {'model': ErrorDetail},
    },
)
def get_mcp_usage(
    name: McpNamePath,
) -> Union[McpUsageResponse, ErrorDetail, HTTPValidationError]:
    """
    List agents and skills that use an MCP server
    """
    return service.get_mcp_usage(name)


@app.get('/probe', response_model=ProbeOk, responses={'503': {'model': ProbeError}})
def probe() -> Union[ProbeOk, ProbeError]:
    """
    Check service and database health
    """
    try:
        return service.probe()
    except Exception as exc:
        return JSONResponse(status_code=503, content={"error": str(exc)})
