# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-08-25T12:26:01+00:00

from __future__ import annotations

from typing import Annotated, Optional, Union

from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import AfterValidator

from . import service
from .generated.api.models import (
    ErrorDetail,
    HTTPValidationError,
    KnowledgeInput,
    KnowledgeListResponse,
    KnowledgeName,
    KnowledgeNameResponse,
    KnowledgeResponse,
    KnowledgeUsageResponse,
    ProbeError,
    ProbeOk,
)


def _knowledge_name(value: str) -> str:
    # Generated KnowledgeName is a RootModel; FastAPI path params must be scalars.
    return KnowledgeName.model_validate(value).root


KnowledgeNamePath = Annotated[str, AfterValidator(_knowledge_name)]

app = FastAPI(
    title='Knowledge',
    description='Knowledge registry service',
    version='0.1.0',
)


@app.get('/api/v1/knowledge', response_model=KnowledgeListResponse)
def list_knowledge() -> KnowledgeListResponse:
    """
    List all knowledge
    """
    return service.list_knowledge()


@app.get(
    '/api/v1/knowledge/{name}',
    response_model=KnowledgeResponse,
    responses={'404': {'model': ErrorDetail}, '422': {'model': HTTPValidationError}},
)
def get_knowledge(
    name: KnowledgeNamePath,
) -> Union[KnowledgeResponse, ErrorDetail, HTTPValidationError]:
    """
    Get knowledge by name
    """
    return service.get_knowledge(name)


@app.post(
    '/api/v1/knowledge/{name}',
    response_model=KnowledgeNameResponse,
    status_code=201,
    responses={
        '400': {'model': ErrorDetail},
        '409': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
    },
)
def create_knowledge(
    name: KnowledgeNamePath, body: KnowledgeInput = ...
) -> Union[KnowledgeNameResponse, ErrorDetail, HTTPValidationError]:
    """
    Create knowledge
    """
    return service.create_knowledge(name, body)


@app.put(
    '/api/v1/knowledge/{name}',
    response_model=KnowledgeNameResponse,
    responses={
        '400': {'model': ErrorDetail},
        '404': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
    },
)
def update_knowledge(
    name: KnowledgeNamePath, body: KnowledgeInput = ...
) -> Union[KnowledgeNameResponse, ErrorDetail, HTTPValidationError]:
    """
    Replace knowledge
    """
    return service.update_knowledge(name, body)


@app.delete(
    '/api/v1/knowledge/{name}',
    response_model=None,
    status_code=204,
    responses={
        '404': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
        '409': {'model': ErrorDetail},
        '502': {'model': ErrorDetail},
    },
)
def delete_knowledge(
    name: KnowledgeNamePath,
) -> Optional[Union[ErrorDetail, HTTPValidationError]]:
    """
    Delete knowledge
    """
    service.delete_knowledge(name)


@app.get(
    '/api/v1/knowledge/{name}/usage',
    response_model=KnowledgeUsageResponse,
    responses={
        '404': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
        '502': {'model': ErrorDetail},
    },
)
def get_knowledge_usage(
    name: KnowledgeNamePath,
) -> Union[KnowledgeUsageResponse, ErrorDetail, HTTPValidationError]:
    """
    List agents and skills that use knowledge
    """
    return service.get_knowledge_usage(name)


@app.get('/probe', response_model=ProbeOk, responses={'503': {'model': ProbeError}})
def probe() -> Union[ProbeOk, ProbeError]:
    """
    Check service and database health
    """
    try:
        return service.probe()
    except Exception as exc:
        return JSONResponse(status_code=503, content={"error": str(exc)})
