# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-08-24T00:14:15+00:00

from __future__ import annotations

from typing import Annotated, Optional, Union

from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import AfterValidator, constr

from . import service
from .generated.api.models import (
    ErrorDetail,
    HTTPValidationError,
    ProbeError,
    ProbeOk,
    ReferenceListResponse,
    SkillInput,
    SkillListResponse,
    SkillName,
    SkillNameResponse,
    SkillResponse,
    SkillUsageResponse,
    ToolListResponse,
)


def _skill_name(value: str) -> str:
    # Generated SkillName is a RootModel; FastAPI path params must be scalars.
    return SkillName.model_validate(value).root


SkillNamePath = Annotated[str, AfterValidator(_skill_name)]

app = FastAPI(
    title='Skill',
    description='Skill registry service',
    version='0.1.0',
)


@app.get('/api/v1/skills', response_model=SkillListResponse)
def list_skills() -> SkillListResponse:
    """
    List all skills
    """
    return service.list_skills()


@app.get('/api/v1/skills/tools', response_model=ToolListResponse)
def list_tools() -> ToolListResponse:
    """
    List tools that skills may require
    """
    return service.list_tools()


@app.get(
    '/api/v1/skills/usage/knowledge/{knowledge_name}',
    response_model=ReferenceListResponse,
)
def list_knowledge_usage(knowledge_name: constr(min_length=1)) -> ReferenceListResponse:
    """
    List skills that reference a knowledge source
    """
    return service.list_knowledge_usage(knowledge_name)


@app.get('/api/v1/skills/usage/mcp/{mcp_name}', response_model=ReferenceListResponse)
def list_mcp_usage(mcp_name: constr(min_length=1)) -> ReferenceListResponse:
    """
    List skills that reference an MCP server
    """
    return service.list_mcp_usage(mcp_name)


@app.get(
    '/api/v1/skills/{name}',
    response_model=SkillResponse,
    responses={
        '404': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
    },
)
def get_skill(name: SkillNamePath) -> Union[SkillResponse, ErrorDetail, HTTPValidationError]:
    """
    Get a skill by name
    """
    return service.get_skill(name)


@app.post(
    '/api/v1/skills/{name}',
    response_model=SkillNameResponse,
    status_code=201,
    responses={
        '400': {'model': ErrorDetail},
        '409': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
    },
)
def create_skill(
    name: SkillNamePath, body: SkillInput = ...
) -> Union[SkillNameResponse, ErrorDetail, HTTPValidationError]:
    """
    Create a skill
    """
    return service.create_skill(name, body)


@app.put(
    '/api/v1/skills/{name}',
    response_model=SkillNameResponse,
    responses={
        '400': {'model': ErrorDetail},
        '404': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
    },
)
def update_skill(
    name: SkillNamePath, body: SkillInput = ...
) -> Union[SkillNameResponse, ErrorDetail, HTTPValidationError]:
    """
    Replace a skill
    """
    return service.update_skill(name, body)


@app.delete(
    '/api/v1/skills/{name}',
    response_model=None,
    status_code=204,
    responses={
        '404': {'model': ErrorDetail},
        '409': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
        '502': {'model': ErrorDetail},
    },
)
def delete_skill(name: SkillNamePath) -> Optional[Union[ErrorDetail, HTTPValidationError]]:
    """
    Delete a skill
    """
    service.delete_skill(name)


@app.get(
    '/api/v1/skills/{name}/usage',
    response_model=SkillUsageResponse,
    responses={
        '404': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
        '502': {'model': ErrorDetail},
    },
)
def get_skill_usage(
    name: SkillNamePath,
) -> Union[SkillUsageResponse, ErrorDetail, HTTPValidationError]:
    """
    List agents that use a skill
    """
    return service.get_skill_usage(name)


@app.get('/probe', response_model=ProbeOk, responses={'503': {'model': ProbeError}})
def probe() -> Union[ProbeOk, ProbeError]:
    """
    Check service and database health
    """
    try:
        return service.probe()
    except Exception as exc:
        return JSONResponse(status_code=503, content={"error": str(exc)})
