# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-08-25T12:47:34+00:00

from __future__ import annotations

from typing import Annotated, Optional, Union

from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import AfterValidator, constr

from . import service
from .generated.api.models import (
    CrewInput,
    CrewListResponse,
    CrewName,
    CrewNameResponse,
    CrewResponse,
    ErrorDetail,
    HTTPValidationError,
    ProbeError,
    ProbeOk,
    ReferenceListResponse,
)


def _crew_name(value: str) -> str:
    # Generated CrewName is a RootModel; FastAPI path params must be scalars.
    return CrewName.model_validate(value).root


CrewNamePath = Annotated[str, AfterValidator(_crew_name)]

app = FastAPI(
    title='Crew',
    description='Crew management service',
    version='0.1.0',
)


@app.get('/api/v1/crews', response_model=CrewListResponse)
def list_crews() -> CrewListResponse:
    """
    List all crews
    """
    return service.list_crews()


@app.get('/api/v1/crews/usage/agent/{agent_name}', response_model=ReferenceListResponse)
def list_agent_usage(agent_name: constr(min_length=1)) -> ReferenceListResponse:
    """
    List crews that reference an agent
    """
    return service.list_agent_usage(agent_name)


@app.get(
    '/api/v1/crews/{name}',
    response_model=CrewResponse,
    responses={'404': {'model': ErrorDetail}, '422': {'model': HTTPValidationError}},
)
def get_crew(
    name: CrewNamePath,
) -> Union[CrewResponse, ErrorDetail, HTTPValidationError]:
    """
    Get a crew by name
    """
    return service.get_crew(name)


@app.post(
    '/api/v1/crews/{name}',
    response_model=CrewNameResponse,
    status_code=201,
    responses={'409': {'model': ErrorDetail}, '422': {'model': HTTPValidationError}},
)
def create_crew(
    name: CrewNamePath, body: CrewInput = ...
) -> Union[CrewNameResponse, ErrorDetail, HTTPValidationError]:
    """
    Create a crew
    """
    return service.create_crew(name, body)


@app.put(
    '/api/v1/crews/{name}',
    response_model=CrewNameResponse,
    responses={'404': {'model': ErrorDetail}, '422': {'model': HTTPValidationError}},
)
def update_crew(
    name: CrewNamePath, body: CrewInput = ...
) -> Union[CrewNameResponse, ErrorDetail, HTTPValidationError]:
    """
    Replace a crew
    """
    return service.update_crew(name, body)


@app.delete(
    '/api/v1/crews/{name}',
    response_model=None,
    status_code=204,
    responses={'404': {'model': ErrorDetail}, '422': {'model': HTTPValidationError}},
)
def delete_crew(
    name: CrewNamePath,
) -> Optional[Union[ErrorDetail, HTTPValidationError]]:
    """
    Delete a crew
    """
    service.delete_crew(name)


@app.get('/probe', response_model=ProbeOk, responses={'503': {'model': ProbeError}})
def probe() -> Union[ProbeOk, ProbeError]:
    """
    Check service and database health
    """
    try:
        return service.probe()
    except Exception as exc:
        return JSONResponse(status_code=503, content={"error": str(exc)})
