apiVersion: v1
kind: Service
metadata:
  name: builder
  labels:
    app.kubernetes.io/name: builder
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: builder
  ports:
    - name: http
      port: 8080
      targetPort: http
