# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-08-25T13:06:54+00:00

from __future__ import annotations

from typing import Annotated, Optional, Union

from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import AfterValidator, constr

from . import service
from .generated.api.models import (
    AgentInput,
    AgentListResponse,
    AgentName,
    AgentNameResponse,
    AgentResponse,
    AgentUsageResponse,
    ErrorDetail,
    HTTPValidationError,
    ProbeError,
    ProbeOk,
    ReferenceListResponse,
)


def _agent_name(value: str) -> str:
    # Generated AgentName is a RootModel; FastAPI path params must be scalars.
    return AgentName.model_validate(value).root


AgentNamePath = Annotated[str, AfterValidator(_agent_name)]

app = FastAPI(
    title='Agent',
    description='Agent registry service',
    version='0.1.0',
)


@app.get('/api/v1/agents', response_model=AgentListResponse)
def list_agents() -> AgentListResponse:
    """
    List all agents
    """
    return service.list_agents()


@app.get(
    '/api/v1/agents/usage/knowledge/{knowledge_name}',
    response_model=ReferenceListResponse,
)
def list_knowledge_usage(knowledge_name: constr(min_length=1)) -> ReferenceListResponse:
    """
    List agents that reference a knowledge source
    """
    return service.list_knowledge_usage(knowledge_name)


@app.get('/api/v1/agents/usage/mcp/{mcp_name}', response_model=ReferenceListResponse)
def list_mcp_usage(mcp_name: constr(min_length=1)) -> ReferenceListResponse:
    """
    List agents that reference an MCP server
    """
    return service.list_mcp_usage(mcp_name)


@app.get(
    '/api/v1/agents/usage/skill/{skill_name}', response_model=ReferenceListResponse
)
def list_skill_usage(skill_name: constr(min_length=1)) -> ReferenceListResponse:
    """
    List agents that reference a skill
    """
    return service.list_skill_usage(skill_name)


@app.get(
    '/api/v1/agents/{name}',
    response_model=AgentResponse,
    responses={'404': {'model': ErrorDetail}, '422': {'model': HTTPValidationError}},
)
def get_agent(
    name: AgentNamePath,
) -> Union[AgentResponse, ErrorDetail, HTTPValidationError]:
    """
    Get an agent by name
    """
    return service.get_agent(name)


@app.post(
    '/api/v1/agents/{name}',
    response_model=AgentNameResponse,
    status_code=201,
    responses={'409': {'model': ErrorDetail}, '422': {'model': HTTPValidationError}},
)
def create_agent(
    name: AgentNamePath, body: AgentInput = ...
) -> Union[AgentNameResponse, ErrorDetail, HTTPValidationError]:
    """
    Create an agent
    """
    return service.create_agent(name, body)


@app.put(
    '/api/v1/agents/{name}',
    response_model=AgentNameResponse,
    responses={'404': {'model': ErrorDetail}, '422': {'model': HTTPValidationError}},
)
def update_agent(
    name: AgentNamePath, body: AgentInput = ...
) -> Union[AgentNameResponse, ErrorDetail, HTTPValidationError]:
    """
    Replace an agent
    """
    return service.update_agent(name, body)


@app.delete(
    '/api/v1/agents/{name}',
    response_model=None,
    status_code=204,
    responses={
        '404': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
        '409': {'model': ErrorDetail},
        '502': {'model': ErrorDetail},
    },
)
def delete_agent(
    name: AgentNamePath,
) -> Optional[Union[ErrorDetail, HTTPValidationError]]:
    """
    Delete an agent
    """
    service.delete_agent(name)


@app.get(
    '/api/v1/agents/{name}/usage',
    response_model=AgentUsageResponse,
    responses={
        '404': {'model': ErrorDetail},
        '422': {'model': HTTPValidationError},
        '502': {'model': ErrorDetail},
    },
)
def get_agent_usage(
    name: AgentNamePath,
) -> Union[AgentUsageResponse, ErrorDetail, HTTPValidationError]:
    """
    List crews that use an agent
    """
    return service.get_agent_usage(name)


@app.get('/probe', response_model=ProbeOk, responses={'503': {'model': ProbeError}})
def probe() -> Union[ProbeOk, ProbeError]:
    """
    Check service and database health
    """
    try:
        return service.probe()
    except Exception as exc:
        return JSONResponse(status_code=503, content={"error": str(exc)})
